### ISSUE TITLE
After some levels the confetti rain does not stop

### ISSUE THREAD

**Issue by stared** [Quantum-Game/quantum-game-2#209]
E.g.:

![image](https://user-images.githubusercontent.com/1001610/80452562-d4318880-8926-11ea-931e-06b9ad8e720b.png)

**Comment by ask4physics** [comment]
Should be a level loading issue. Needed to hit the 'refresh' button in order to clear the confetti, as it is distracting:

![Level 4](https://user-images.githubusercontent.com/64779944/87134343-2437ae80-c2cb-11ea-9f0f-24088ab80b92.PNG)

@stared would it be possible to remove the confetti effects altogether?

**Comment by stared** [comment]
@ask4physics Do you consider the bug distracting (we certainly want to solve it), or confetti in general (we are happy to add an option, if needed)?

**Comment by ask4physics** [comment]
hi Piotr, come to think of it, confetti effects are cool 😎, so it would be great if we could iron out this bug.
Just a quick question:
(i) Is the vue-confetti [plugin](https://github.com/alexandermendes/vue-confetti) rendered server-side or client-side only?
